Use plist to manage arguments and environment for macos swarm plugin
voxpupuli/puppet-jenkins pull request #899
Opened 2019-01-11 14:04 UTC by anutting

#### Pull Request (PR) description
This change removes the start up script for macOS and moves the arguments to the plist template.

#### This Pull Request (PR) fixes the following issues
Fixes #892 - The jenkins-slave file is no longer used.

2019-01-11 17:05 UTC, anutting commented
@rnelson0 ui_user is the user the swarm plugin uses to authenticate with the jenkins master (along with ui_pass). The slave class uses the puppet stdlib shellquoted function with ui_user then saves that to quoted_ui_user. The slave_user is the user account created on the slave to manage the swarm plugin and own any files.

2019-01-14 14:12 UTC, anutting commented on templates/org.jenkins-ci.slave.jnlp.plist.erb
> +  <% if @quoted_ui_pass -%>
sure, I'll get that going.

2019-01-14 14:36 UTC, rnelson0 commented
@anutting in #892, the issue is at lines 309-316 of `manifests/slave.pp` (and a few other places @dhoppe identified), but this PR does not modify those lines, which is why I'm not sure how it addresses the described failures.

2019-01-15 15:22 UTC, mmarseglia commented
@rnelson0 the problem we found is that on macos the script used to invoke the service did not work.  we found that by removing the script and defining all variables in the plist the service started correctly.

2019-01-15 18:00 UTC, anutting commented
@rnelson0 the file created on line 309 of manifests/slave.pp (jenkins-slave) used to be sourced from the start.slave.sh file created in manifests/slave.pp line 259 (which I removed in my commit). Since my PR no longer uses the jenkins-slave file, it fixes #892.

2019-01-18 19:36 UTC, Dan33l commented
If you rebase you will get more dedicated messages during acceptance about fail due to error or idempotency. cf #900

2019-01-22 14:45 UTC, anutting commented
@Dan33l Thank you for your suggestion to rebase master. It seems that didn't fix any of the Travis CI jobs.

@rnelson0 I've implemented your requested changes. Is there anything else needed to get this merged?

Thanks

2019-01-22 16:38 UTC, mmarseglia commented
Given this might be a puppet6 issue and not with our PR may this be merged?

2022-09-16 19:25 UTC, ekohl requested changes

2022-09-16 19:25 UTC, ekohl commented on templates/org.jenkins-ci.slave.jnlp.plist.epp
> +    <string><%= jenkins::slave::_real_java_args -%></string>
Missing a `$` here. Applied in https://github.com/voxpupuli/puppet-jenkins/pull/1057

2022-09-16 19:26 UTC, ekohl commented
I've rebased this and fixed it up in https://github.com/voxpupuli/puppet-jenkins/pull/1057. I did notice labels were missing, but I see you already removed your fork so I think you have no more interest in fixing it up.

2022-09-16 19:26 UTC, closed without merging