modulesync 2.12.0
voxpupuli/puppet-jenkins pull request #962
Opened 2020-04-04 14:29 UTC by bastelfreak

modulesync 2.12.0

2020-04-05 22:07 UTC, ekohl commented on .rubocop.yml
> -RSpec/MessageSpies:
For now this should be kept until someone fixes the actual code

2020-04-05 22:08 UTC, ekohl commented on spec/spec_helper.rb
> -# Rough conversion of grepping in the puppet source:
These custom facts should be kept in. I started to work on support for this in voxpupuli-test but until then, please keep it.

2020-11-25 18:08 UTC, ekohl requested changes
Needs a rebase (and probably some squashing of commits).

2020-11-26 00:34 UTC, ekohl commented
18.04 suffers from https://github.com/jenkinsci/packaging/pull/198. There's a workaround mentioned.

2021-01-08 15:41 UTC, genebean commented
looks like the plugin ownership is an issue here too @ekohl. Do you want me to dig into that?

2021-01-08 15:45 UTC, ekohl commented
> looks like the plugin ownership is an issue here too @ekohl. Do you want me to dig into that?

Please do. For me it did work in a libvirt VM on CentOS 7 and couldn't quite figure out why it fails in Docker.

I haven't looked at Ubuntu 18.04 since this PR adds it.

2021-01-08 16:23 UTC, genebean commented
Documented in #1002 and working on a fix in #1001

2021-01-08 19:59 UTC, genebean commented
@ekohl I see that the plugin stuff not being idempotent is not new (#839) - is this something we have to get fixed before moving forward or can it be a known issue for the moment? I ask because one of the reasons we started poking at this was that the currently released version does not have the right gpg keys for CentOS based servers while the code on master does. I am all for getting this fixed but it is starting to look like a non-trivial thing to deal with.

2021-01-11 14:41 UTC, ekohl commented
This looks like the same problems as we have in master so I'm merging it.

2021-01-11 14:41 UTC, merged